# ~/.config/kitty/kitty.conf

# FUENTE
font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12.5

# TRANSPARENCIA y DIFUMINADO
background_opacity 0.85
dynamic_background_opacity yes
background_blur 0

# COLORES
foreground #cdd6f4
background #0B0F1A
selection_foreground #0b0f1a
selection_background #cdd6f4
url_color #80aaff

kitty, ahora tus secundarios (color2,6,10,14) se ponen en modo celeste puro #7ecfff, como si Kitty se hubiera tragado un vibrador RGB y escupiera aqua vibes sin piedad:

color0 #0b0f1a  
color1 #7ebaff  
color2 #7ecfff  
color3 #cdd6f4  
color4 #7ebaff  
color5 #7ebaff  
color6 #7ecfff  
color7 #cdd6f4  
color8 #0b0f1a  
color9 #7ebaff  
color10 #7ecfff  
color11 #cdd6f4  
color12 #7ebaff  
color13 #7ebaff  
color14 #7ecfff  
color15 #cdd6f4

# CURSOR
cursor_shape beam
cursor_blink_interval 0.5

# MOUSE
mouse_hide_when_typing yes

# SCROLLBACK
scrollback_lines 10000

# TECLAS COPIAR/PEGAR
map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard

# SONIDO
enable_audio_bell no
